###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: php-docker-memcached

    redis:
      image: redis:alpine
      container_name: php-docker-redis

    mariadb:
      image: mariadb:10.1
      container_name: php-docker-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=Blink182
        - MYSQL_DATABASE=phpdb
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password

    webserver:
      image: nginx:alpine
      container_name: php-docker-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-docker-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

